services:
  auth:
    build: 
      context: ./go-auth
    ports:
      - "8000:8000"
    env_file:
      - ./go-auth/.env

  test:
    build:
      context: ./test-momentum
    ports:
      - "8081:8081"
    depends_on:
      - auth

  video:
    build:
      context: ./video-service
    ports:
      - "8084:8084"
    env_file:
      - ./video-service/.env
    depends_on:
      - auth

  chat:
    build:
      context: ./chat-service
    ports:
      - "8083:8083"
    env_file:
      - ./chat-service/.env
    depends_on:
      - auth

  post:
      build:
        context: ./post-service
      ports:
        - "8082:8082"
      env_file:
        - ./post-service/.env
      depends_on:
        - auth
        - video